# Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

# postgres database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: password
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: postgres
JPA_SHOW_SQL: false
